typography_spectrum: 0.6223073224537075
color:
  brandColors:
    - '#fbfbf7'
    - '#97bbd9'
    - '#3b291a'
    - '#b4614a'
    - '#005481'
  brandStrength: 0.4451945808250457
  lightness: 0.13823971757665277
  saturation: 0.9894253879319876
  rhythmicContrast: 0.5347778853029013
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6169559429399669
analytics:
  google: null
  facebook: null
  twitter: null
name: SENSUUM
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
