name: SENSUUM
favicon: null
layout_spectrum: 0.6169559429399669
typography_spectrum: 0.6223073224537075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4451945808250457
  lightness: 0.13823971757665277
  saturation: 0.9894253879319876
  rhythmicContrast: 0.5347778853029013
purpose: []
